### ISSUE TITLE
Unexpected token: operator (<)

### ISSUE THREAD

**Issue by ivanhueso** [ember-cli/ember-cli-uglify#24]
Hi, I'm getting this issue when I try to `ember b -p`. I'm using the latest ember `2.14.0`

    Build failed.
     The Broccoli Plugin: [Fingerprint] failed with:
     SyntaxError: Unexpected token: operator (<)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:86:23)
    at new BroccoliBuildError (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-builder/lib/broccoli-build-error.js:18:29)
    at /Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:508:7)
    at publishRejection (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:443:3)
    at flush (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

    The broccoli plugin was instantiated at:
        at Fingerprint.Plugin (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-asset-rev/lib/fingerprint.js:27:10)
    at Fingerprint (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-asset-rev/lib/fingerprint.js:22:12)
    at new AssetRev (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-asset-rev/lib/asset-rev.js:27:25)
    at AssetRev (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)

**Comment by JoshMesser** [comment]
I'm getting something like this as well. Mine only happens when I attempt a production build.

```
The Broccoli Plugin: [Fingerprint] failed with:
SyntaxError: Name expected
    at JS_Parse_Error.get (eval at <anonymous> (/var/connxus/admin2/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at new BroccoliBuildError (/var/connxus/admin2/node_modules/broccoli-builder/lib/broccoli-build-error.js:18:29)
    at /var/connxus/admin2/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/var/connxus/admin2/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/var/connxus/admin2/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/var/connxus/admin2/node_modules/rsvp/dist/rsvp.js:508:7)
    at publishRejection (/var/connxus/admin2/node_modules/rsvp/dist/rsvp.js:443:3)
    at flush (/var/connxus/admin2/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
The broccoli plugin was instantiated at:
    at Fingerprint.Plugin (/var/connxus/admin2/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/var/connxus/admin2/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/var/connxus/admin2/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
    at Fingerprint (/var/connxus/admin2/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
    at new AssetRev (/var/connxus/admin2/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
    at AssetRev (/var/connxus/admin2/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/var/connxus/admin2/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/var/connxus/admin2/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/var/connxus/admin2/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
```

**Comment by Turbo87** [comment]
@ivanhueso what does your `targets.js` file looks like and what version of `ember-cli-uglify` are you using?

**Comment by 0xadada** [comment]
Also getting this problem when i changed `config/targets.js` from:
```javascript
module.exports = {
   browsers: [
    'ie 9',
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
   ]
 };
```

to:
```javascript
module.exports = {
  browsers: [
    '> 6% in US' /* http://browserl.ist/?q=%3E+6%25+in+US */
  ]
};
```

## Error

```
+- build
|  |
|  +- build
|    - building app to `tmp/deploy-dist` using buildEnv `production`...
[BABEL] Note: The code generator has deoptimised the styling of "advisor/inline-assets.js" as it exceeds the max of "500KB".
Warning: ignoring input sourcemap for vendor/ember/ember.prod.js because ENOENT: no such file or directory, open '/Users/distiller/advisor/tmp/source_map_concat-input_base_path-ymjpraau.tmp/vendor/ember/ember.prod.map'
cleaning up
cleaning up...
|    - build failed
|
+- didFail
Error: The Broccoli Plugin: [Fingerprint] failed with:
SyntaxError: Unexpected token: name (token)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/distiller/advisor/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at new BroccoliBuildError (/Users/distiller/advisor/node_modules/broccoli-builder/lib/broccoli-build-error.js:18:29)
    at /Users/distiller/advisor/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/Users/distiller/advisor/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/distiller/advisor/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/distiller/advisor/node_modules/rsvp/dist/rsvp.js:508:7)
    at publishRejection (/Users/distiller/advisor/node_modules/rsvp/dist/rsvp.js:443:3)
    at flush (/Users/distiller/advisor/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

The broccoli plugin was instantiated at: 
    at Fingerprint.Plugin (/Users/distiller/advisor/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/distiller/advisor/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/distiller/advisor/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
    at Fingerprint (/Users/distiller/advisor/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
    at new AssetRev (/Users/distiller/advisor/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
    at AssetRev (/Users/distiller/advisor/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/Users/distiller/advisor/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/Users/distiller/advisor/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/distiller/advisor/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)

|
Pipeline aborted
```

## Details

`"ember-cli-uglify": "^1.2.0",`

```bash
ember version --verbose
ember-cli: 2.14.2
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64
```

**Comment by rwjblue** [comment]
@0xadada - In order to process ES6+ code in uglify you need ember-cli-uglify@2 (1.x will only support ES5).

**Comment by 0xadada** [comment]
@rwjblue I just upgrade to 2.16, with `ember-cli-ugify` 2, seems to have resolved that particular issue and revealed another:

```
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
Error: ENOENT: no such file or directory, open '/Users/ron/cinch/advisor/tmp/uglify_writer-input_base_path-kCMItc3z.tmp/assets/maps/swiper.min.js.map'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at UglifyWriter.processFile (/Users/ron/cinch/advisor/node_modules/broccoli-uglify-sourcemap/index.js:101:41)
    at /Users/ron/cinch/advisor/node_modules/broccoli-uglify-sourcemap/index.js:65:16
    at Array.forEach (native)
    at /Users/ron/cinch/advisor/node_modules/broccoli-uglify-sourcemap/index.js:55:25
    at Array.forEach (native)
    at UglifyWriter.build (/Users/ron/cinch/advisor/node_modules/broccoli-uglify-sourcemap/index.js:54:19)
    at /Users/ron/cinch/advisor/node_modules/broccoli-plugin/read_compat.js:93:34

The broccoli plugin was instantiated at:
    at Fingerprint.Plugin (/Users/ron/cinch/advisor/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/ron/cinch/advisor/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
    at Fingerprint (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
    at new AssetRev (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
    at AssetRev (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/Users/ron/cinch/advisor/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/ron/cinch/advisor/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
```

**Comment by bertdeblock** [comment]
I assume this issue is no longer relevant, given the switch to terser, so closing for now.
