### ISSUE TITLE
ember production build is failed

### ISSUE THREAD

**Issue by sunglam** [ember-cli/ember-cli-uglify#242]
Version Summary:
ember-cli-uglify@3.0.0
two versions of moment at different path
moment@2.22.2
moment@2.29.1
terser@4.8.0
 
=================================================================================

ENV Summary:

  TIME: Mon Nov 23 2020 14:37:29 GMT+0530 (India Standard Time)
  TITLE: ember
  ARGV:
  - /Users/sursingh/.nvm/versions/node/v10.19.0/bin/node
  - /Users/sursingh/.nvm/versions/node/v10.19.0/bin/ember
  - build
  - --environment=production
  EXEC_PATH: /Users/sursingh/.nvm/versions/node/v10.19.0/bin/node
  TMPDIR: /var/folders/df/y8t2mcrn5dz8033nqzh2736r0000gp/T
  SHELL: /bin/bash
  PATH:
  - /Users/sursingh/.nvm/versions/node/v10.19.0/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64 
  FREEMEM: 1167257600
  TOTALMEM: 17179869184
  UPTIME: 441860
  LOADAVG: 2.833984375,3.78271484375,3.796875
  CPUS:
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  ENDIANNESS: LE
  VERSIONS:
- ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.9.3
  - icu: 64.2
  - modules: 64
  - napi: 5
  - nghttp2: 1.39.2
  - node: 10.19.0
  - openssl: 1.1.1d
  - tz: 2019c
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.55
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: Unexpected token: eof (undefined)
    at ee (/Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:19541)
    at c (/Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:28244)
    at l (/Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:28335)
    at f (/Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:28388)
    at N (/Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:38492)
    at /Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:30588
    at /Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:28976
    at /Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:32320
    at /Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:32430
    at /Users/sursingh/alarms-ui/node_modules/terser/dist/bundle.min.js:1:28976
  - code: [undefined]
  - codeFrame: Unexpected token: eof (undefined)
  - errorMessage: Unexpected token: eof (undefined)
        at UglifyWriter
-~- created here: -~-
    at UglifyWriter.Plugin (/Users/sursingh/alarms-ui/node_modules/broccoli-uglify-sourcemap/node_modules/broccoli-plugin/index.js:7:31)
at new UglifyWriter (/Users/sursingh/alarms-ui/node_modules/broccoli-uglify-sourcemap/index.js:38:10)
    at UglifyWriter (/Users/sursingh/alarms-ui/node_modules/broccoli-uglify-sourcemap/index.js:33:12)
    at Class.postprocessTree (/Users/sursingh/alarms-ui/node_modules/ember-cli-uglify/index.js:54:50)
    at projectOrAddon.addons.reduce (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>:null:null)
    at addonProcessTree (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:856:12)
    at EmberApp.host.addonPostprocessTree (/Users/sursingh/alarms-ui/node_modules/ember-auto-import/js/auto-import.js:108:20)
    at EmberApp.toTree (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1788:17)
    at module.exports (/Users/sursingh/alarms-ui/ember-cli-build.js:57:14)
    at Builder.readBuildFile (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/sursingh/alarms-ui/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/Users/sursingh/alarms-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)

**Comment by sunglam** [comment]
Please have a look at the above issue

**Comment by sandstrom** [comment]
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.

If there is an actual code issue, steps to reproduce (and ideally a failing test-case) is a good start.

Since this code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻

**Comment by rwjblue** [comment]
Seems very unlikely that we'll be able to do anything to help here (no repro, no example of the code that triggers the error, etc). 

I'm going to close for now...

**Comment by gorner** [comment]
Not sure if the original poster ever figured out the issue at the time, but I came across this yesterday and couldn't figure it out until I realized we'd recently had moment.js bumped. Apparently there was a change in moment that caused an [issue](https://github.com/adopted-ember-addons/ember-moment/issues/328) with terser, which can be resolved by bumping ember-cli-moment-shim to v3.8.0, or alternatively using ember-moment v10+.
