### ISSUE TITLE
Production builds failing without IE11 as build target

### ISSUE THREAD

**Issue by amk221** [ember-cli/ember-cli-uglify#254]
Here is a minimal reproduction: https://github.com/amk221/-ember-terser-failure/commit/b8b937d737ddebb17afcb4f957ed5c5a0cf6887d

Steps to re-create:

* Create a fresh ember-cli app
* Include use of `{ ...this }`
* _Remove IE11 from build targets_
* Build for prod

```
Build Error (TerserWriter)

Cannot read property 'references' of undefined
```

<details>
  <summary>Full error log</summary>
=================================================================================

ENV Summary:

  TIME: Thu Feb 18 2021 14:32:30 GMT+0000 (Greenwich Mean Time)
  TITLE: ember
  ARGV:
  - /Users/andrew/.nodenv/versions/10.16.0/bin/node
  - /Users/andrew/.nodenv/versions/10.16.0/bin/ember
  - build
  - --environment=production
  EXEC_PATH: /Users/andrew/.nodenv/versions/10.16.0/bin/node
  TMPDIR: /var/folders/jr/2d1_15pj3jd2s5d5gzxwq75h0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/andrew/.nodenv/versions/10.16.0/bin
  - /usr/local/Cellar/nodenv/1.4.0/libexec
  - /Users/andrew/.jenv/shims
  - /Users/andrew/.nodenv/shims
  - /Users/andrew/.rbenv/shims
  - /usr/local/opt/mysql@5.7/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Library/Apple/usr/bin
  PLATFORM: darwin x64
  FREEMEM: 912154624
  TOTALMEM: 34359738368
  UPTIME: 621535
  LOADAVG: 11.6513671875,8.17626953125,7.015625
  CPUS:
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 4
  - nghttp2: 1.34.0
  - node: 10.16.0
  - openssl: 1.1.1b
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.52
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'references' of undefined
    at TreeTransformer.before (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:11843:51)
    at AST_Expansion.transform (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5385:41)
    at /Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5401:21
    at doit (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:112:23)
    at MAP (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:137:52)
    at do_list (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5400:12)
    at /Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5559:23
    at AST_Object.transform (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5388:13)
    at /Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5449:45
    at AST_Return.transform (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5388:13)
  - code: [undefined]
  - codeFrame: Cannot read property 'references' of undefined
  - errorMessage: Cannot read property 'references' of undefined
        at TerserWriter
-~- created here: -~-
    at new Plugin (/Users/andrew/src/examples/-ember-terser-failure/node_modules/broccoli-terser-sourcemap/node_modules/broccoli-plugin/dist/index.js:45:33)
    at new TerserWriter (/Users/andrew/src/examples/-ember-terser-failure/node_modules/broccoli-terser-sourcemap/index.js:30:5)
    at Class.postprocessTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli-terser/index.js:61:14)
    at projectOrAddon.addons.reduce (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:843:12)
    at EmberApp.host.addonPostprocessTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-auto-import/js/auto-import.js:103:20)
    at EmberApp.toTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:1666:17)
    at module.exports (/Users/andrew/src/examples/-ember-terser-failure/ember-cli-build.js:23:14)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Cannot read property 'references' of undefined
        at TerserWriter
-~- created here: -~-
    at new Plugin (/Users/andrew/src/examples/-ember-terser-failure/node_modules/broccoli-terser-sourcemap/node_modules/broccoli-plugin/dist/index.js:45:33)
    at new TerserWriter (/Users/andrew/src/examples/-ember-terser-failure/node_modules/broccoli-terser-sourcemap/index.js:30:5)
    at Class.postprocessTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli-terser/index.js:61:14)
    at projectOrAddon.addons.reduce (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:843:12)
    at EmberApp.host.addonPostprocessTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-auto-import/js/auto-import.js:103:20)
    at EmberApp.toTree (/Users/andrew/src/examples/-ember-terser-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:1666:17)
    at module.exports (/Users/andrew/src/examples/-ember-terser-failure/ember-cli-build.js:23:14)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: TerserWriter
  - originalErrorMessage: Cannot read property 'references' of undefined
  - stack: TypeError: Cannot read property 'references' of undefined
    at TreeTransformer.before (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:11843:51)
    at AST_Expansion.transform (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5385:41)
    at /Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5401:21
    at doit (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:112:23)
    at MAP (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:137:52)
    at do_list (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5400:12)
    at /Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5559:23
    at AST_Object.transform (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5388:13)
    at /Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5449:45
    at AST_Return.transform (/Users/andrew/src/examples/-ember-terser-failure/node_modules/terser/dist/bundle.min.js:5388:13)

=================================================================================

</details>

**Comment by rwjblue** [comment]
This is a bug in terser, would you mind reporting there?

<img width="781" alt="Screen Shot 2021-02-18 at 9 47 50 AM" src="https://user-images.githubusercontent.com/12637/108373910-66648f00-71ce-11eb-9889-0fce54fe3f24.png">

**Comment by rwjblue** [comment]
Just playing around with that, it seems that it is specifically around spreading `...this`. You can avoid the specific error by using `Object.assign({}, this, defaults)` (just to unblock you).

**Comment by amk221** [comment]
Thanks for the unblock

**Comment by amk221** [comment]
Fixed upstream
