### ISSUE TITLE
Issue with source maps enabled

### ISSUE THREAD

**Issue by aklkv** [ember-cli/ember-cli-uglify#30]
ember-cli-uglify@2.0.0

I am getting an error on production build `ember build --environment=production`:

```bash
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
Error: ENOENT: no such file or directory, open '/Users/uni_mac/Desktop/semios/customer-web-app/tmp/uglify_writer-input_base_path-MSPzFITj.tmp/assets/popper.js.map'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at UglifyWriter.processFile (/Users/uni_mac/Desktop/semios/customer-web-app/node_modules/broccoli-uglify-sourcemap/index.js:101:41)
    at /Users/uni_mac/Desktop/semios/customer-web-app/node_modules/broccoli-uglify-sourcemap/index.js:65:16
    at Array.forEach (<anonymous>:null:null)
    at /Users/uni_mac/Desktop/semios/customer-web-app/node_modules/broccoli-uglify-sourcemap/index.js:55:25
    at Array.forEach (<anonymous>:null:null)
    at UglifyWriter.build (/Users/uni_mac/Desktop/semios/customer-web-app/node_modules/broccoli-uglify-sourcemap/index.js:54:19)
    at /Users/uni_mac/Desktop/semios/customer-web-app/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/uni_mac/Desktop/semios/customer-web-app/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/uni_mac/Desktop/semios/customer-web-app/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/uni_mac/Desktop/semios/customer-web-app/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/uni_mac/Desktop/semios/customer-web-app/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

If I disable source maps build completes successfully.

**Comment by kjhangiani** [comment]
experiencing the same error when going from ember-cli 2.15.x to 2.16.x (and correspondingly updating `ember-cli-uglify`)

is there a workaround for now?  even if I have to fork temporarily?

**Comment by kjhangiani** [comment]
seems related to: https://github.com/ember-cli/ember-cli-uglify/issues/29 in that a missing sourcemap is now causing a fatal error.

guessing the sourcemap in question in our situation (from some addon most likely) has always been missing, but the change from `source-map-url` 0.3.0 to 0.4.0 as a result of upgrading `ember-cli-uglify` is causing `production` builds to now fail

**Comment by stefanpenner** [comment]
should be now addressed.
