### ISSUE TITLE
using es6-7 features appears to break this module

### ISSUE THREAD

**Issue by mgenev** [ember-cli/ember-cli-uglify#5]
I get these errors:

```
ember build --environment=production
version: 0.2.3
Build failed.
Unexpected token operator «*», expected punc «(»
Error
    at new JS_Parse_Error (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:684:41)
    at token_error (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:688:9)
    at expect_token (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:701:9)
    at expect (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:704:36)
    at function_ (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:964:9)
    at expr_atom (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1193:24)
    at maybe_unary (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1363:19)
    at expr_ops (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1398:24)
    at maybe_conditional (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1403:20)
    at maybe_assign (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1427:20)
    at expression (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1446:20)
```

**Comment by mgenev** [comment]
this was due to using the wrong babel setting, https://github.com/mgenev/how-to-sane/pull/84

**Comment by Ramblurr** [comment]
So what was the actual fix?

**Comment by Polve** [comment]
I'm interested in how to fix this, too.
